language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install poetry
  - poetry install

script:
  - poetry run py.test --cov-report term --cov=rd_client

after_success:
  - bash <(curl -s https://codecov.io/bash)
