language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install poetry
  - poetry install

script:
  - poetry run py.test --cov-report term --cov=rd_client
